title: "Kalee Li "
logo: /assets/img/kaleePic_logo.png
description: "Data Engineer, Solution Engineer & Analyst specializing in database management, data pipelines, ETL, and system development. Passionate about optimizing data workflows and analytics."
linkedin: https://www.linkedin.com/in/kalee-l-566433184/

github: 
  is_user_page: true
  owner_url: "https://github.com/Kalee914"
google_analytics: G-93NCR9ERQX
theme: jekyll-theme-minimal

