title: "Kalee Li "
logo: /assets/img/kaleePic_logo.png
description: "Data, Solution, and Process Engineer and Analyst specializing in data solutions, system performance analysis, bottleneck identification, and process optimization. I develop and implement data infrastructure, ETL pipelines, and technical solutions to drive efficiency and enhance analytics."
linkedin: https://www.linkedin.com/in/kalee-l-566433184/

github: 
  is_user_page: true
  owner_url: "https://github.com/Kalee914"
google_analytics: G-93NCR9ERQX
theme: jekyll-theme-minimal

