title: "Ka Lee Li"
logo: /assets/img/Kalee.png
Email: ""
description: "I’m an aspiring Database Engineer with a strong foundation in data analysis, database management, and software development. I am currently pursuing a Computer Science degree at Southern New Hampshire University, I am proficient in various programming languages and tools. With solid communication skills, I am eager to explore opportunities in both database engineering and web/system development."
url: "https://kalee914.github.io"
theme: jekyll-theme-minimal

