title: "Ka Lee Li"
logo: /assets/img/Kalee.png
description:"Phone: 646-251-3040<br>Email: kalee914@gmail.com<br>LinkedIn: <a href='https://www.linkedin.com/in/kalee-l-566433184/'>Linkedin Profile</a>"
baseurl: "" # Leave blank 
url: "https://kalee914.github.io"
theme: jekyll-theme-minimal

