title: "Ka Lee Li"
logo: /assets/img/KaleePic.png
description: "Computer Science Student at SNHU | Skilled in Data Analysis, DB Management & Development | Aspiring Database Engineer | Exploring Web/System Dev"
linkedin: https://www.linkedin.com/in/kalee-l-566433184/

github: 
  is_user_page: true
  owner_url: "https://github.com/Kalee914"

theme: jekyll-theme-minimal

