title: "Ka Lee Li"
logo: /assets/img/Kalee.png
description: "Phone: 646-251-3040, Email: kalee914@gmail.com, LinkedIn: https://www.linkedin.com/in/kalee-l-566433184/"
baseurl: "" # Leave blank 
url: "https://kalee914.github.io"
theme: jekyll-theme-minimal

