title: "Ka Lee Li"
logo: /assets/img/Kalee.png
description: "Aspiring Database Engineer with a strong foundation in data analysis, database management, and software development. Proficient in various programming languages and tools, with strong communication skills. Seeking a database engineering role while exploring web and system development opportunities"
baseurl: "" # Leave blank 
url: "https://kalee914.github.io"
theme: jekyll-theme-minimal

